<?php if ($this->pageCount):?>
    <div>
        <ul class="pagination pagination-centered">
            <?php if (isset($this->previous)):?>
            <li><a href="<?=$this->url($this->route, ['p' => $this->previous])?>"><<</a></li>
            <?php else:?>
            <li class="disabled"><a href="#"><<</a></li>
            <?php endif?>

            <?php foreach ($this->pagesInRange as $page):?>
                <?php if ($page != $this->current):?>
                <li><a href="<?=$this->url($this->route, ['p' => $page])?>"><?=$page?></a></li>
                <?php else:?>
                <li class="active"><a href="#"><?=$page?></a></li>
                <?php endif?>
            <?php endforeach?>

            <?php if (isset($this->next)): ?>
            <li><a href="<?=$this->url($this->route, ['p' => $this->next])?>">>></a></li>
            <?php else:?>
            <li class="disabled"><a href="#">>></a></li>
            <?php endif?>
        </ul>
    </div>
<?php endif?>
