<div>
	<header>
		<a href="#"><?=$this->escapeHtml($this->comment->getUser()->getUsername())?></a> -
        <span>
            <?=$this->translate("posted")?> <?=$this->timeago($this->comment->getCreated())?>
        </span>
	</header>
	<p><?=$this->escapeHtml($this->comment->getMessage())?></p>

	<p>
		<small>
			<a href="<?=$this->url("reply", [
					"link" => $this->comment->getLink()->getId(),
					"parent" => $this->comment->getId(),
				]
			)?>"><?=$this->translate("Reply")?></a>
		</small>
	</p>
</div>
