<?=$this->doctype()?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?=$this->headTitle('Thing')?>

        <?=$this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

        <?=$this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')?>
        <?=$this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))?>
    </head>

    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?=$this->url('home')?>">
                      <?=$this->translate('.thing')?>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?=$this->url('home')?>"><?=$this->translate('Home')?></a></li>
                        <li class="active"><a href="<?=$this->url('submit')?>"><?=$this->translate('Submit')?></a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <?php if ($user = $this->identity()):?>
                        <li class="active"><a href="#"><?=$this->escapeHtml($user->getUsername())?></a></li>
                        <li class="active"><a href="<?=$this->url('logout')?>"><?=$this->translate('Logout')?></a></li>
                        <?php else:?>
                        <li class="active"><a href="<?=$this->url('register')?>"><?=$this->translate('Register')?></a></li>
                        <li class="active"><a href="<?=$this->url('login')?>"><?=$this->translate('Login')?></a></li>
                        <?php endif?>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?=$this->content?>
            <hr>
            <footer>
                <p>&copy; <?=date('Y')?> <a href="http://github.com/sdgoij">sdgoij</a> <?=$this->translate('All rights reserved.')?></p>
            </footer>
        </div>
        <?=$this->inlineScript()?>
    </body>

</html>
